- src/main/java/com/eternalcode/core/EternalCore.java
- src/main/java/com/eternalcode/core/user/CreateUserListener.java
- src/main/java/com/eternalcode/core/user/User.java
- src/main/java/com/eternalcode/core/utils/BenchmarkUtils.java
> GH-15 Update User and CreateUserListener.

- src/main/java/com/eternalcode/core/EternalCore.java
- src/main/java/com/eternalcode/core/command/implementations/InventoryOpenCommand.java
- src/main/java/com/eternalcode/core/configuration/MessagesConfiguration.java
- src/main/java/com/eternalcode/core/listeners/inventory/InventoryClickListener.java
- src/main/java/com/eternalcode/core/listeners/inventory/InventoryCloseListener.java
- src/main/java/com/eternalcode/core/listeners/player/PlayerCommandPreprocessListener.java
- src/main/java/com/eternalcode/core/listeners/sign/SignChangeListener.java
- src/main/java/com/eternalcode/core/utils/BenchmarkUtils.java
+ InventoryOpenCommand
+ Zmiana układu paczek
+ Dodanie colored signs
+ Dodanie unknown command
> Commands & Listeners

- eternalcore/build.gradle.kts
**Please describe the changes made by this PR and why they need to be merged: this PR include a super ultra hiper extra solution for excluding and relocating packages into shadowJar file**
**Status: Successfully ✅**
> Simplify relocate and exclude operation

- eternalcore/build.gradle.kts
**Please describe the changes made by this PR and why they need to be merged: this PR include a super ultra hiper extra solution for excluding and relocating packages into shadowJar file**
**Status: Successfully ✅**
> GH-151 Simplify exclude and relocate operation

- eternalcore/src/main/java/com/eternalcode/core/home/command/HomeCommand.java
**Please describe the changes made by this PR and why they need to be merged: Added bypass permission for /home command**
**Status: Successfuly and Tested**
**Issue:** #178
> GH-180 Add bypass permission for home

- eternalcore/src/main/java/com/eternalcode/core/shared/PositionAdapter.java
**Please describe the changes made by this PR and why they need to be merged: Add messages to some exceptions, It's pretty useful!**
**Status: Successfully**
> GH-187 Add messages to some exceptions

- eternalcore/src/main/java/com/eternalcode/core/chat/notification/Notice.java
- eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
- eternalcore/src/main/java/com/eternalcode/core/configuration/lang/ENMessagesConfiguration.java
- eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
- eternalcore/src/main/java/com/eternalcode/core/language/Messages.java
- eternalcore/src/main/java/com/eternalcode/core/language/OptionalMessageExtractor.java
- eternalcore/src/main/java/com/eternalcode/core/listener/player/PlayerDeathListener.java
- eternalcore/src/main/java/com/eternalcode/core/listener/player/PlayerJoinListener.java
- eternalcore/src/main/java/com/eternalcode/core/listener/player/PlayerQuitListener.java
**ET-122**
**Please describe the changes made by this PR and why they need to be merged:**
- **Move welcome title/subtitle to language config**
- **Move quit/join message to language config**
- **Move first join message to language conifg**
- **Move death message to language config and implmenet random death message**
**Status: Successfully and tested**
> GH-191 Move welcome messages to language configuration

- CHANGELOGS.md
- eternalcore/src/main/java/com/eternalcode/core/configuration/lang/ENMessagesConfiguration.java
- eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
- eternalcore/src/main/java/com/eternalcode/core/home/command/SetHomeCommand.java
Previously there was a bug that the /warp command did not display the name of the warp after it was created. I corrected this bug, and fixed the same bug in the house system.
> GH-245 Placeholder names to uppercase

- eternalcore/src/main/java/com/eternalcode/core/chat/ChatManagerCommand.java
- eternalcore/src/main/java/com/eternalcode/core/command/implementation/EnchantCommand.java
- eternalcore/src/main/java/com/eternalcode/core/command/implementation/SkullCommand.java
- eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/AnvilCommand.java
- eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/DisposalCommand.java
- eternalcore/src/main/java/com/eternalcode/core/teleport/request/TpaDenyCommand.java
> GH-272 Remove useless aliases (Resolve #262)

- CHANGELOGS.md
- eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/InventoryClearCommand.java
- eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/InventoryOpenCommand.java
- eternalcore/src/main/java/com/eternalcode/core/configuration/lang/ENMessagesConfiguration.java
- eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
- eternalcore/src/main/java/com/eternalcode/core/language/Messages.java
This PR fixes a critical bug where you could copy your items by opening your inventory
> GH-263 Add target check to open inventory command (Resolve #256)

- eternalcore/src/main/java/com/eternalcode/core/EternalCore.java
- eternalcore/src/main/java/com/eternalcode/core/command/argument/SpeedArgument.java
- eternalcore/src/main/java/com/eternalcode/core/command/implementation/SpeedCommand.java
> GH-261 Add speed argument for correct tabulation (Resolve #261)

- CHANGELOGS.md
- eternalcore/src/main/java/com/eternalcode/core/EternalCore.java
- eternalcore/src/main/java/com/eternalcode/core/command/argument/LocationArgument.java
- eternalcore/src/main/java/com/eternalcode/core/command/argument/WorldArgument.java
- eternalcore/src/main/java/com/eternalcode/core/translation/Translation.java
- eternalcore/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> GH-279 Add language support to world and location argument

- eternalcore/src/main/java/com/eternalcode/core/afk/AfkCommand.java
- eternalcore/src/main/java/com/eternalcode/core/afk/AfkSettings.java
- eternalcore/src/main/java/com/eternalcode/core/chat/ChatSettings.java
- eternalcore/src/main/java/com/eternalcode/core/chat/feature/reportchat/HelpOpCommand.java
- eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
- eternalcore/src/main/java/com/eternalcode/core/delay/Delay.java
- eternalcore/src/main/java/com/eternalcode/core/delay/DelaySettings.java
- eternalcore/src/main/java/com/eternalcode/core/translation/Translation.java
- eternalcore/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Implement Delay to:
- AfkCommand
- HelpOpCommand
> GH-313 Add delay domain and system

- README.md
- core/build.gradle.kts
This PR beautifies the README.md, and additionally sorts the `plugins {}` block in `build.gradle.kts` alphabetically.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
No tests required.
> GH-320 Sort gradle plugins alphabetically, readme touchup

- README.md
> GH-353 Add features to README

- core/src/main/java/com/eternalcode/core/EternalCore.java
- core/src/main/java/com/eternalcode/core/command/argument/NoticeTypeArgument.java
- core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
- core/src/main/java/com/eternalcode/core/feature/essentials/FeedCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/FlyCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/HealCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/container/AnvilCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/container/CartographyTableCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/container/DisposalCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/container/EnderchestCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/container/GrindstoneCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/container/InventoryClearCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/container/StonecutterCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/container/WorkbenchCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/gamemode/GameModeCommand.java
- core/src/main/java/com/eternalcode/core/feature/essentials/item/GiveCommand.java
- core/src/main/java/com/eternalcode/core/notification/Notice.java
- core/src/main/java/com/eternalcode/core/notification/NoticeType.java
- core/src/main/java/com/eternalcode/core/notification/Notification.java
- core/src/main/java/com/eternalcode/core/notification/adventure/AdventureNotificationAnnouncer.java
- core/src/main/java/com/eternalcode/core/translation/Translation.java
- core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> GH-359 Add reply to target

- core/src/main/java/com/eternalcode/core/EternalCore.java
- core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
- core/src/main/java/com/eternalcode/core/feature/warp/WarpCommand.java
- core/src/main/java/com/eternalcode/core/feature/warp/WarpInventory.java
- core/src/main/java/com/eternalcode/core/feature/warp/config/WarpConfigItem.java
- core/src/main/java/com/eternalcode/core/feature/warp/config/WarpInventoryItem.java
- core/src/main/java/com/eternalcode/core/language/config/LanguageConfiguration.java
- core/src/main/java/com/eternalcode/core/translation/Translation.java
- core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
- core/src/main/java/com/eternalcode/core/util/AdventureUtil.java
- core/src/main/java/com/eternalcode/core/util/legacy/Legacy.java
> GH-391 Add WarpInventory system

- eternalcore-core/src/main/java/com/eternalcode/core/database/wrapper/HomeRepositoryOrmLite.java
> GH-437 Fix home deletion

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/EnchantCommand.java
- eternalcore-plugin/build.gradle.kts
Fix #466, but need testing before merge this.
> GH-466 Add option to enchant item in hand of another player

- README.md
Preview: https://github.com/EternalCodeTeam/EternalCore/tree/setup-readme-to-ger-ready-for-release/README.md
> GH-472 Setup readme to get ready for release

- eternalcore-core/build.gradle.kts
- eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
- eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
- eternalcore-core/src/main/java/com/eternalcode/core/updater/UpdaterController.java
- eternalcore-core/src/main/java/com/eternalcode/core/updater/UpdaterService.java
> GH-484 Add updater 

- eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/home/command/HomeCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Fixes #493 
On localhost server.
> GH-493 Instant teleport to home if one home was set.

- eternalcore-core/build.gradle.kts
- eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
- eternalcore-core/src/main/java/com/eternalcode/core/adventure/legacy/Legacy.java
- eternalcore-core/src/main/java/com/eternalcode/core/adventure/legacy/LegacyColorProcessor.java
- eternalcore-core/src/main/java/com/eternalcode/core/adventure/resolver/CenterTagResolver.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/container/DisposalCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/container/InventoryOpenCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemLoreCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemNameCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/listener/player/PlayerLoginListener.java
- eternalcore-core/src/main/java/com/eternalcode/core/listener/sign/SignChangeListener.java
The **LegacyColorProcessor** and **Legacy** classes were moved to a different package called 'adventure.legacy'. A new feature for center-aligned text was added using the **CenterTagResolver** class. To support this, **pixel-width** libraries were included in the build file.
Very thanks for @rchomczyk for psychical support.
https://github.com/EternalCodeTeam/EternalCore/assets/65517973/a9e3d4ae-1bf5-4cf1-830f-877e1e6cf260
Fixes #481
> GH-481 Add feature to support center-aligned text

- eternalcore-core/build.gradle.kts
> GH-494 Fix logger warn

- eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpCommand.java
/warp add/remove -> /setwarp /delwarp /warp
> GH-525 Update warp command routes

- eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/reportchat/HelpOpCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/reportchat/HelpOpSettings.java
Fix invalid cooldown in delay between messages sent through helpop feature; add a dedicated section in configuration for helpop to make configuration more transparent
Please delete options that are not relevant.
> GH-534 Fix invalid cooldown in delay between messages sent through helpop feature

- eternalcore-core/src/main/java/com/eternalcode/core/feature/privatechat/PrivateChatCommands.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Prefer use of state placeholder in socialspy feature; minor fixes in Polish translation
Fixes # (issue)
> GH-535 Prefer use of state placeholder in socialspy feature

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/HatCommand.java
Before:
https://github.com/EternalCodeTeam/EternalCore/assets/65517973/c173ad9e-2495-472b-9874-c00f63ad01eb
After:
https://github.com/EternalCodeTeam/EternalCore/assets/65517973/4221c0fa-ac7a-4414-bc14-b7af18c86e4d
> GH-536 Fix hat command item duplication bug.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/RepairCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Add unique translation for repair all, to allow for even more flexibility in translations
> GH-549 Add unique translation for repair all

- eternalcore-core/src/main/java/com/eternalcode/core/util/ReflectUtil.java
Fixed error of using System#out#println
> GH-556 Fix error of using System#out#println

- eternalcore-core/src/main/java/com/eternalcode/core/configuration/contextual/ConfigItem.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpInventory.java
> GH-487 Fix warp inventory operator cooldown.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/container/InventoryClearCommand.java
Added permission for /clear command.
> GH-573 Very importanto fix adding clear command

- eternalcore-core/src/main/java/com/eternalcode/core/notice/PlatformBroadcasterAdventureImpl.java
> GH-570 Fix subtitle and title don't send while another part of title is not send

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherArgument.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherCommand.java
> GH-568 Implement ButcherArgument to suggest between 1-5.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/home/HomeArgument.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/home/HomeCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/AbstractViewerBroadcastArgument.java
- eternalcore-core/src/main/java/com/eternalcode/core/litecommand/handler/NoticeBroadcastHandler.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Fixes: #569 
Make improvements to the code by adding a "home" list instead of displaying a "not exist" message. Additionally, fix the tab completion feature and include a notice handler for broadcasting notifications.
> GH-569 Add home list, fix tabulation in home-side commands.

- eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/firstjoin/FirstJoinController.java
> GH-587 Implement teleport to spawn on first join

- eternalcore-core/src/main/java/com/eternalcode/core/feature/reportchat/HelpOpCommand.java
> GH-598 Remove one of helpop message displayed to sender.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/RepairCommand.java
> GH-613 Add another permission to repair all and armor.

- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> GH-599 Fix mistake in default translation.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/SkullCommand.java
Fixes: #600 
https://github.com/EternalCodeTeam/EternalCore/assets/65517973/439a7b8f-a47d-4dee-a5b6-977af879a627
> GH-600 Fix skull texture parse.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/EnchantCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> GH-595 Add enchant messages for player.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/home/HomeCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/home/HomePlaceholderSetup.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> GH-614 Send "You don't have any home" if player don't have homes instead of empty home list.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportToPositionCommand.java
Fixes: GH-602
https://github.com/EternalCodeTeam/EternalCore/assets/65517973/73bd9f1e-ef83-49f9-acae-da6d8440427e
> GH-602 Use Location Argument in tppos.

- eternalcore-core/src/main/java/com/eternalcode/core/bridge/litecommand/argument/PlayerArgument.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportCommand.java
> GH-601 Add PlayerArgument, fix /tp command usage.

- eternalcore-core/src/main/java/com/eternalcode/core/notice/NoticeTextType.java
- eternalcore-core/src/main/java/com/eternalcode/core/notice/NoticeType.java
- eternalcore-core/src/main/java/com/eternalcode/core/notice/PlatformBroadcasterAdventureImpl.java
> GH-584 Fix subtitle with title notice from config.

- buildSrc/src/main/kotlin/Versions.kt
Simplify and fix a problem with a building project.
> GH-629 Remove `companion object` line and switch class to object

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/FlyCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/GodCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
> GH-642 Add separated messages to enabled and disabled state.

- .github/workflows/publish.yml
- buildSrc/src/main/kotlin/eternalcore-publish.gradle.kts
- eternalcore-api/build.gradle.kts
- eternalcore-api/src/main/java/com/eternalcode/core/EternalCoreApi.java
- eternalcore-api/src/main/java/com/eternalcode/core/feature/afk/Afk.java
- eternalcore-api/src/main/java/com/eternalcode/core/feature/afk/AfkReason.java
- eternalcore-api/src/main/java/com/eternalcode/core/feature/afk/AfkService.java
- eternalcore-api/src/main/java/com/eternalcode/core/feature/afk/event/AfkSwitchEvent.java
- eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
- eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreApiImpl.java
- eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreEnvironment.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkReason.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkServiceImpl.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkTask.java
Fixes #422 
```java
import com.eternalcode.core.EternalCoreApi;
import com.eternalcode.core.EternalCoreApiProvider;
import com.eternalcode.core.feature.afk.AfkService;
import org.bukkit.plugin.java.JavaPlugin;
public class MyAwesomePlugin extends JavaPlugin {
@Override
public void onEnable() {
EternalCoreApi provide = EternalCoreApiProvider.provide();
AfkService afkService = provide.getAfkService();
// my awesome functions need afkService ...
}
}
```
> GH-422 Create developer api structures, add afk developer api.

- .github/workflows/publish.yml
- buildSrc/src/main/kotlin/eternalcore-publish.gradle.kts
- eternalcore-api/build.gradle.kts
- eternalcore-api/src/main/java/com/eternalcode/core/EternalCoreApi.java
- eternalcore-api/src/main/java/com/eternalcode/core/feature/afk/Afk.java
- eternalcore-api/src/main/java/com/eternalcode/core/feature/afk/AfkReason.java
- eternalcore-api/src/main/java/com/eternalcode/core/feature/afk/AfkService.java
- eternalcore-api/src/main/java/com/eternalcode/core/feature/afk/event/AfkSwitchEvent.java
- eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
- eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreApiImpl.java
- eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreEnvironment.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkReason.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkServiceImpl.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkTask.java
Approved by a few people: https://github.com/EternalCodeTeam/EternalCore/pull/645, but someone used a merge option to merge instead of squash.
Fixes #422 
```java
import com.eternalcode.core.EternalCoreApi;
import com.eternalcode.core.EternalCoreApiProvider;
import com.eternalcode.core.feature.afk.AfkService;
import org.bukkit.plugin.java.JavaPlugin;
public class MyAwesomePlugin extends JavaPlugin {
@Override
public void onEnable() {
EternalCoreApi provide = EternalCoreApiProvider.provide();
AfkService afkService = provide.getAfkService();
// my awesome functions need afkService ...
}
}
```
> GH-422 Create developer api structures, add afk developer api. 

- README.md
> GH-647 Add instruction for EternalCoreAPI to readme

- eternalcore-core/src/main/java/com/eternalcode/core/bridge/litecommand/LiteCommandsSetup.java
- eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/AutoMessageService.java
> GH-653 Player count requirement to send auto message

- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherArgument.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/MobEntityArgument.java
> GH-670 Butcher command arguments fix

- README.md
> [ci skip] GH-676 Improve several things in README.md file.

- README.md
> GH-695 Update badges in README

- eternalcore-core/src/main/java/com/eternalcode/core/injector/bean/processor/BeanProcessor.java
- eternalcore-core/src/main/java/com/eternalcode/core/injector/bean/processor/BeanProcessorRegistry.java
No description needed, it just looks better and is easier to understand
> GH-734 Improve Bean Processor.

- eternalcore-api/src/main/java/com/eternalcode/core/EternalCoreApi.java
- eternalcore-api/src/main/java/com/eternalcode/core/feature/language/LanguageService.java
- eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreApiImpl.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/language/Language.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/language/LanguageServiceImpl.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/TranslationManager.java
- eternalcore-core/src/main/java/com/eternalcode/core/user/UserSettingsImpl.java
> GH-662 Add language api.

- eternalcore-core/src/main/java/com/eternalcode/core/bridge/litecommand/argument/PlayerArgument.java
> GH-757 Resolve case sensitivity issue in command execution for Minecraft nicknames

- buildSrc/src/main/kotlin/Versions.kt
- buildSrc/src/main/kotlin/eternalcore-repositories.gradle.kts
- eternalcore-plugin/build.gradle.kts
- eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/Dependency.java
- eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyCollector.java
- eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoadEntry.java
- eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoadResult.java
- eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoaderImpl.java
- eternalcore-plugin/src/main/java/com/eternalcode/core/loader/pom/PomXmlScanner.java
- eternalcore-plugin/src/main/java/com/eternalcode/core/loader/relocation/RelocationHandler.java
Resolve: #799
A - Rollczi's computer 6x 4.90GHz, 48GB, 40Mbps
B - vLucky's computer 12Mbps
C - VPS 4x 3,7 GHz, 8GB, 730Mbps
A - 90s (38s + 52s)
B - 98s (45s + 53s)
C - 54s (19s + 35s) 
A - 21s (15s + 6s)
B - 31s (18s + 13s)
C - 12s (10s + 2s)
A - **4,2x** faster
B - **3,2x** faster
C - **4,5x** faster
(first part of the time represents searching for dependency, second represents downloading and relocation)
> GH-799 Improve dependency loader performance with parallel downloading and relocation.

- buildSrc/src/main/kotlin/Versions.kt
- buildSrc/src/main/kotlin/eternalcore-repositories.gradle.kts
- eternalcore-core/build.gradle.kts
- eternalcore-core/src/main/java/com/eternalcode/core/configuration/ConfigurationManager.java
- eternalcore-core/src/main/java/com/eternalcode/core/notice/EternalCoreBroadcastImpl.java
- eternalcore-core/src/main/java/com/eternalcode/core/notice/EternalCoreNoticeBukkitResolver.java
- eternalcore-core/src/main/java/com/eternalcode/core/notice/NoticeService.java
- eternalcore-core/src/main/java/com/eternalcode/core/notice/NoticeTextType.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
- eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Updated Multification dependency to 1.1.2 from 1.0.2. Refactored related classes to use the updated API, including changes in Notice and Configuration classes. Added new NoticeResolverRegistry for the NoticeService class.
> GH-813 Update Multification dependency and refactor related classes

- eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/Teleport.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/TeleportTask.java
- eternalcore-core/src/main/java/com/eternalcode/core/util/DurationUtil.java
https://github.com/user-attachments/assets/eea3f363-2939-4b17-873e-3f060458e608
> GH-821 Fix teleport timer format, fix teleport timer that's spam on chat.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/TeleportTask.java
As if anything, only the order of the code has changed:trollface:
> G-824 Fix timer to cancel move.

- eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
> GH-836 Remove uncessary spaces in config.

- buildSrc/src/main/kotlin/Versions.kt
- eternalcore-core/src/main/java/com/eternalcode/core/configuration/composer/DurationComposer.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/chat/ChatCommand.java
- eternalcore-core/src/main/java/com/eternalcode/core/util/DurationUtil.java
> GH-913 Fix chat delay is not save to configuration.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/gamemode/GameModeCommand.java
> GH-947 Fix missing permission for gamemode shortcut's

- eternalcore-core/src/main/java/com/eternalcode/core/feature/enchant/EnchantCommand.java
https://github.com/user-attachments/assets/08118a8f-5c4e-49e0-af84-ff796df699d0
> GH-1000 Removed doubled message in /enchant command

- eternalcore-core/src/main/java/com/eternalcode/core/feature/heal/HealCommand.java
Fixes: #1036 #1037 
Fillup oxygen:
https://github.com/user-attachments/assets/498e284a-64ca-4777-b01e-7a33b4307a3b
Support custom max health:
https://github.com/user-attachments/assets/7457609b-8386-48f9-a518-5051dfccb741
> GH-1036 GH-1037 Fillup oxygen, support custom health level.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/teleportrandomplayer/TeleportToRandomPlayerCommand.java
Fixes: #1056 
tested with my friends:
https://github.com/user-attachments/assets/78c09268-0613-4f73-ba71-344564b97d3e
> GH-1056 Fix `/tprp` teleport always to same player.

- eternalcore-core/src/main/java/com/eternalcode/core/feature/speed/SpeedArgument.java
- eternalcore-core/src/main/java/com/eternalcode/core/feature/speed/SpeedCommand.java
https://github.com/user-attachments/assets/9f5a4098-aea0-46f5-9234-135af1f61081
> GH-1168 Change `speed` argument type from `Integer` to `Double`.
