EternalCodeTeam/EternalCore

src/main/java/com/eternalcode/core/EternalCore.java, src/main/java/com/eternalcode/core/chat/ChatManager.java, src/main/java/com/eternalcode/core/chat/ChatUtils.java, src/main/java/com/eternalcode/core/chat/PlayerChatListener.java, src/main/java/com/eternalcode/core/command/implementations/GcCommand.java, src/main/java/com/eternalcode/core/user/User.java, src/main/java/com/eternalcode/core/user/UserService.java
Hej... Ogólnie to czemu chcę usunąć z User, UserManager, ChatManager zależności od Minecraft?
Odpowiedź jest prosta: Tego kodu nie da się swobodnie testować (trzeba robić mocki i dodawać bukkit api) i nagina to założenia wzorca projektowego [Dependency inversion principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle). Kod modelu tzn. np. User, Order, Invite, ChatManager itd. jest kodem wysokiej ważności i nie powinien być zależny od minecrafta.
Prosty przykład, zakładamy że chcę przetestować ChatManager w testach jednostkowych na starym kodzie wymagało by to Playera, co oznacza że musimy mockować API Bukkita i się bawić w tego typu rzeczy.
Po zamianach możemy bez problemu używać metod z ChatManager tworząc sobie nowe UUID.
=> Bukkit&kyori dependency

eternalcore/src/main/java/com/eternalcode/core/command/configurator/CommandConfiguration.java
Hi, im add template to add custom command config for command configurator
Result:
```yaml
commands:
eternalcore:
name: "eternal-core"
aliases:
- "eternal"
permissions:
- "eternalcore.eternalcore"
```
=> GH-233 Add command template for command config

eternalcore/src/main/java/com/eternalcode/core/chat/feature/reportchat/HelpOpCommand.java, eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java, eternalcore/src/main/java/com/eternalcode/core/translation/Translation.java, eternalcore/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java, eternalcore/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
The name "cooldown" says very little, so I decided to exclude it in some places. In offensive language, it can be misinterpreted. "Delay" says a lot more, and sounds a lot better!
=> GH-287 Exclude "cooldown"

core/src/main/java/com/eternalcode/core/EternalCore.java, core/src/main/java/com/eternalcode/core/teleport/command/TeleportUpCommand.java, core/src/main/java/com/eternalcode/core/translation/Translation.java, core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java, core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
The update introduces the '/tpup' command, which teleports the player to the highest block above them.
The tests have been conducted on a local server.
Instruction:
- Run the /tpup command
_After executing the command, the player should appear on the block that is highest above their head._
=> GH-386 Added TpUpCommand

core/src/main/java/com/eternalcode/core/EternalCore.java
Currently, the Stopwatch is only stopped on the VM stop/kill. This PR fixes it, and stops the running timer on the end of enabling.
=> GH-395 Stop the Stopwatch properly

eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java, eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/spawn/SpawnRespawnController.java, eternalcore-core/src/main/java/com/eternalcode/core/listener/player/PlayerDeathListener.java, eternalcore-core/src/main/java/com/eternalcode/core/listener/player/PlayerRespawnListener.java
PR dodaje możliwość ustawienia w configu czy gracz ma się teleportować na spawna po śmierci.
Dodałem również dodatkowego checka w PlayerDeathListener ponieważ gdy gracz użył komendy "**/kill**" wyrzucało błąd
https://github.com/EternalCodeTeam/EternalCore/pull/434/files#diff-1ff580cabf582e48ca59eeda20a77fb296faa0336a6e0df54b4d96afc3e31514
=> GH-434 Add teleport to spawn on death & additional check

eternalcore-core/src/main/java/com/eternalcode/core/feature/home/command/SetHomeCommand.java
Changed the home set logic in **SetHomeCommand** to prioritize the existing home check before the home limit check. Previously, the user was first informed about reaching the home limit even when the existing home was being overwritten. This update modulates the sequence for improved feedback and user experience.
Fixes #489 
https://github.com/EternalCodeTeam/EternalCore/assets/65517973/c6730cb4-52c1-490f-ab3f-63614629142f
=> GH-489 Reorder home limit check in SetHomeCommand

eternalcore-core/src/main/java/com/eternalcode/core/feature/reportchat/HelpOpCommand.java
A player unique identifier has been added to the **HelpOpCommand**, allowing the noticeService to associate messages with the player sending them.
Fixes #498
=> GH-498 Fix message about helpop send, just add player uuid to sender notice.

eternalcore-core/build.gradle.kts
The plugin could not run, while opted to use MariaDB's, PostgreSQL's and H2's driver, because of its lack in classloader.
=> GH-529 Add a missing database driver for MariaDB

eternalcore-core/build.gradle.kts, renovate.json
The plugin could not run, while opted to use MariaDB's, PostgreSQL's and H2's driver, because of its lack in classloader.
=> GH-530 Add missing database drivers

eternalcore-core/src/main/java/com/eternalcode/core/feature/spawn/SpawnCommand.java
The default message implementation in PL and EN translation is {PLAYER} but, replacement is {SENDER}, I changed this in replacement from {SENDER} to {PLAYER}, because, in my opinion, it is best and {SENDER} is not making sense.
=> GH-545 Change the placeholder from "{SENDER}" to "{PLAYER}".

eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportToRandomPlayerCommand.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
This pr adding `/teleport-to-random-player` command (alias: /tprp) including new option in configuration.
This command help admins of servers to spy players, command has option to disable random teleport to player with operator level.
Resolve: #541 issue.
=> GH-541 Add teleport to random player features (tprp command).

eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkTask.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/vanish/VanishService.java
Prevent vanished players being marked as AFK. 
It should work with most of the plugins for vanish functionality, as it is being resolved with use of commonly established standard. I have tested the plugin with use of SuperVanish and it seems to work fine.
=> GH-550 Prevent vanished players being marked as AFK

eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/request/TpaCommand.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
=> GH-577 Add TpaCommand to support ignored players

eternalcore-core/src/main/java/com/eternalcode/core/bridge/litecommand/argument/EnchantmentArgument.java
Use conversion to lowercase of argument in enchantment resolver to prevent an exception caused due to not matching to namespaced key's pattern.
Please delete options that are not relevant.
=> GH-751 Fix enchantment argument resolver

eternalcore-api/src/main/java/com/eternalcode/core/feature/chat/event/restrict/ChatRestrictEvent.java, eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreEnvironment.java
Fixes an exception that occurs when slowmode is enabled (e.g., set to 5 seconds) and a user sends messages quickly enough to get limited.
Full exception: https://mclo.gs/mtjw42C
- Enable slowmode using `/chat slowmode 5s`
- Spam
- The user gets notified to slow down, and other players don't see the message.
=> GH-789 Fix ChatRestrictEvent sync usage.

buildSrc/src/main/kotlin/Versions.kt, eternalcore-core/build.gradle.kts, eternalcore-docs-generate/build.gradle.kts
Add caffeine as a library, and relocate it.
Fixes incompatibility with LibertyBans (and possibly other plugins).
More info [in the discord server](https://discord.com/channels/889460117953720351/1025826334435455047/1249739215936426125)
Didn't test yet, I'm committing from a chromebook.
=> GH-791 Fix incompatibility with LibertyBans (and possibly other plugins) by relocate caffeine.

eternalcore-core/src/main/java/com/eternalcode/core/util/DurationUtil.java
Fixes: #790. This is currently the only solution that satisfies me.
The idea is that the format should return a single member of the format "1s" but also take into account the milli-seconds at a later time, so that the format does not return empty text.
=> GH-790 Fix duration format

eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/Dependency.java, eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyCollector.java, eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoadResult.java, eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoaderImpl.java
=> GH-792 Fix updating of libraries. (dependency loader)

README.md, eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/serverlinks/ServerLinksConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/serverlinks/ServerLinksController.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/serverlinks/ServerLinksEntry.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/serverlinks/ServerLinksService.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/serverlinks/package-info.java
**Adds the functionality of customizable server links in the pause menu (ESC).**  
---
🛠️ **Requires Minecraft 1.21+** - feature uses the new `ServerLinks` API added in version 1.21.  
⚠️ **Does not work on older versions!**
---
https://github.com/user-attachments/assets/78d746b3-80bf-4a8c-82f0-6c3853be0978
*Config:*  
```yaml
serverLinks:
sendLinksOnJoin: true
serverLinks:
- :
name: "<rainbow>Discord"
address: "https://discord.gg/v2rkPb4Q2r"
- :
name: "Website"
address: "https://www.eternalcode.pl"
```
=> GH-905 Add server links feature to pause menu (1.21+ only)

eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/AutoMessageCommand.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/AutoMessageRepositoryOrmLite.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/AutoMessageService.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/AutoMessageTable.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/messages/ENAutoMessageMessages.java
The `for` loop added `eq` (equality) conditions for each `UUID`, but it did not correctly combine them using the `OR` operator.
The `or(onlineUniqueIds.size())` method did not work as expected because it did not create a proper logical `OR` condition in SQL.
- Let's assume we have 3 online players: `UUID1`, `UUID2`, `UUID3`.
- Player `UUID2` has ignored messages.
- The faulty query might return an incorrect `ignoredIds` list, such as an empty list.
- As a result, all players (including `UUID2`) received messages, even though `UUID2` had ignored them.
- The corrected query returns an `ignoredIds` list containing only `UUID2`.
- Messages are sent only to `UUID1` and `UUID3`.
- Player `UUID2` does not receive messages, in accordance with their settings.
=> GH-909 Resolve auto-message issues with database query, and message ordering.

eternalcore-core/src/main/java/com/eternalcode/core/feature/seen/SeenCommand.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/seen/messages/ENSeenMessages.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/seen/messages/EnSeenMessages.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/seen/messages/PLSeenMessages.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/seen/messages/SeenMessages.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
=> GH-903 Add seen command feature

eternalcore-core/src/main/java/com/eternalcode/core/feature/teleport/command/TeleportHereCommand.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/teleportrequest/messages/ENTeleportRequestMessages.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/teleportrequest/messages/PLTeleportRequestMessages.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/teleportrequest/messages/TeleportRequestMessages.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/teleportrequest/self/TpaHereCommand.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java, eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Introduced new functionality for teleportation commands, specifically added support for teleporting all players to a single player and sending teleport requests to all players. It also updated the translation files and interfaces to support these new features.
Closes #1034.
=> GH-1034 Add teleport-here all and teleport-here ask-to-all functionality

eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/automessage/AutoMessageConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/butcher/ButcherConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/chat/ChatConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/helpop/HelpOpConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/home/HomesConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/home/command/HomeCommand.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/jail/JailConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/lightning/LightningConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/repair/RepairConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/spawn/SpawnJoinConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/teleportrequest/TeleportRequestConfig.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpConfig.java
Fixes: #1082 
**No migrations are needed; okaeri-configs will update the comments itself, and nothing else has changed. Everything is compatible with the old config.**
**Standard:
Spacing between parent sections; no spacing between configuration options.**
Actual generated config after changes:
```yaml
#
#
#
#
shouldReceivePluginUpdates: true
database:
databaseType: "SQLITE"
hostname: "localhost"
port: 3306
database: "eternalcore"
username: "root"
password: "password"
ssl: false
poolSize: 16
timeout: 30000
join:
teleportToSpawnOnFirstJoin: true
teleportToSpawnOnJoin: false
teleportAsk:
tpaRequestExpire: "1m20s"
tpaTimer: "10s"
teleport:
teleportToSpawnOnDeath: true
teleportToRespawnPoint: true
teleportTimeToSpawn: "5s"
includeOpPlayersInRandomTeleport: false
randomTeleport:
delay: "5s" …
```
=> GH-1082 Move the config sections into dedicated classes. Improve `parent` comments of sections.

eternalcore-core/src/main/java/com/eternalcode/core/feature/vanish/controller/OpenSilentController.java
https://github.com/user-attachments/assets/dc45aeec-2817-4cde-8a23-f47dcc7fdbca
https://github.com/user-attachments/assets/f3121c6f-a8ec-4a8b-b7df-49424c099766
=> GH-1090 Fix rare race condition in SilentContainer.

eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportConfig.java
```yaml
randomTeleport:
delay: "5s"
cooldown: "1m"
radiusType: "WORLD_BORDER_RADIUS"
radius:
minX: -5000
maxX: 5000
minZ: -5000
maxZ: 5000
world: "world"
teleportAttempts: 10
unsafeBlocks:
- "BEDROCK"
- "BUBBLE_COLUMN"
- "CACTUS"
- "COBWEB"
- "FIRE"
- "LAVA"
- "MAGMA_BLOCK"
- "POWDER_SNOW"
- "SEAGRASS"
- "SWEET_BERRY_BUSH"
- "TALL_SEAGRASS"
- "TNT"
- "WATER"
- "WITHER_ROSE"
airBlocks:
- "AIR"
- "STRING"
- "ACTIVATOR_RAIL"
- "ALLIUM"
- "AZURE_BLUET"
- "BLUE_ORCHID"
- "CAVE_AIR"
- "COMPARATOR"
- "CORNFLOWER"
- "DANDELION"
- "DEAD_BUSH"
- "DETECTOR_RAIL"
- "LARGE_FERN"
- "LEVER"
- "LILAC"
- "LILY_OF_THE_VALLEY"
- "ORANGE_TULIP"
- "OXEYE_DAISY"
- "PEONY"
- "PINK_TULIP"
- "POPPY"
- "POWERED_RAIL"
- "RAIL"
- "RED_TULIP"
- "REDSTONE_WIRE"
- "REPEATER"
- "ROSE_BUSH"
- "SHORT_GRASS"
- "SNOW"
- …
```
=> GH-1125 Improve `RandomTeleportConfig` comments for better UX

eternalcore-core/src/main/java/com/eternalcode/core/feature/sleep/PhantomSpawnController.java, eternalcore-core/src/main/java/com/eternalcode/core/feature/sleep/PlayerJoinSleepController.java, eternalcore-paper/src/main/java/com/eternalcode/paper/phantom/PhantomEventInitializer.java, eternalcore-paper/src/main/java/com/eternalcode/paper/phantom/PhantomEventWrapper.java, eternalcore-paper/src/main/java/com/eternalcode/paper/phantom/PhantomSpawnAttemptEvent.java
=> GH-1134 Add permissions allowing to ignore sleep count for night skip and phantom spawn
